trigger:
  - master

pool:
  vmImage: "ubuntu-latest"
strategy:
  matrix:
    Python36:
      python.version: "3.6"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "$(python.version)"
    displayName: "Use Python $(python.version)"

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install torch==1.3.1+cpu torchvision==0.4.2+cpu -f https://download.pytorch.org/whl/torch_stable.html
      pip install -e .
    displayName: "Install dependencies"

  - script: |
      pip install flake8
      flake8 srdatasets tests
    displayName: "Run lint tests"

  - script: |
      pip install pytest pytest-azurepipelines pytest-cov
      pytest --ignore=tests/datasets/test_citeulike.py --cov=srdatasets --cov-report=html tests
    displayName: "pytest"
